### ISSUE TITLE
Error using with ComfyUI on SD1.5 or SDXL model: IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

### ISSUE THREAD

**Issue by timogiles** [42lux/ComfyUI-safety-checker#3]
I can't seem to get this to work.  I'm using the latest ComfyUI but when I run it I get the following error:

Error in ClipSafetyChecker forward method: Dimension out of range (expected to be in range of [-2, 1], but got 2)
Error in nsfw_checker: Dimension out of range (expected to be in range of [-2, 1], but got 2)
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-safety-checker\safety_checker.py", line 190, in nsfw_checker
    checked_image, nsfw = self.safety_checker(images=images, clip_input=safety_checker_input.pixel_values, sensitivity=sensitivity)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-safety-checker\safety_checker.py", line 117, in forward
    special_cos_dist = ClipSafetyChecker.compute_cosine_similarity(image_embeds, self.special_care_embeds)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-safety-checker\safety_checker.py", line 49, in compute_cosine_similarity
    return F.cosine_similarity(embeds.unsqueeze(1), target_embeds, dim=2)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Am I doing something wrong?

**Comment by timogiles** [comment]
Ok Interesting.  I have my ComfyUI nodes just like your suggested picture KSampler --> VAE Decode --> Safety Checker when i get the error.  I tried adding 'Split Image with Alpha' first to remove the integrated mask and I still get the error.  my workflow is now KSampler --> VAE Decode --> Split Image with Alpha --> Safety Checker and that gives the same error as before.

**Comment by timogiles** [comment]
I consulted with 'deepseek-coder-33b-instruct' on the error and it suggested the following change and it is now working:

```
    def compute_cosine_similarity(embeds, target_embeds):
        # Compute the cosine similarity between two sets of embeddings
        # The embeddings are expanded along a new dimension for proper broadcasting
        if len(embeds.shape) == 1:  # If embeds is a 1D tensor
            return F.cosine_similarity(embeds.unsqueeze(0), target_embeds.unsqueeze(0), dim=1)
        else:
            return F.cosine_similarity(embeds, target_embeds, dim=1)
```
